### PR TITLE
fixed search

### PR DESCRIPTION
**Pull request by VasuDevrani**
# Related Issues
- Solves #46 

# Propsed Changes
Sidebar expands when search icon is clicked 

# Additional Info
- any additional Info or context

# Check List
- [x] Test
- [x] Documentation

### CODE REVIEW

**Comment by Chandraprakash-Darji** [comment]
@VasuDevrani This temporary. I am going to add algolia search. There will be btn to open search modal

**Comment by Chandraprakash-Darji** [comment]
Just then removed because I am changing to btn.

**Comment by Chandraprakash-Darji** [comment]
I have make the changes to expand when focus.. If it was closed then it will close when you not focus on input nox

**Comment by VasuDevrani** [comment]
Okay great

**Pull request closed without merging**
