### PR TITLE
Create News for AI Card

### PR DESCRIPTION
**Pull request by logicalahara**
# Related Issues
- Create News for AI Card #17 

# Propsed Changes
- created a new section 'News of AI'
- added static content

# Screenshots
Screenshot 2022-10-15 at 10 46 48 AM

### CODE REVIEW

**Comment by Chandraprakash-Darji** [comment]
@logicalahara solve the error. Gituhb actions failed

**Comment by logicalahara** [comment]
@Chandraprakash-Darji pushed a new commit. Please check.

**Comment by Chandraprakash-Darji** [comment]
Thanks for the contributions

**Comment by logicalahara** [comment]
@Chandraprakash-Darji thanks for the merge !

Could you please add `hacktoberfest-accepted` label ?

**Comment by Chandraprakash-Darji** [comment]
@logicalahara label to issue or pull request

**Comment by logicalahara** [comment]
@Chandraprakash-Darji -> Issue

**Pull request merged**
